services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: vynlo-postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: vynlo_taste
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "96043020"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vynlo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vynlo_taste"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: vynlo-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vynlo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Spring Boot
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: vynlo-backend-prod
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_MAIN_ALLOW_BEAN_DEFINITION_OVERRIDING=true
      - DATABASE_URL=jdbc:postgresql://postgres:5432/vynlo_taste
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=vynlo_taste
      - DB_USER=postgres
      - DB_PASSWORD=96043020
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vynlo_taste
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=96043020
      - SPRING_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/vynlo_taste
      - DB_URL=jdbc:postgresql://postgres:5432/vynlo_taste
      - JDBC_URL=jdbc:postgresql://postgres:5432/vynlo_taste
      - JDBC_DATABASE_URL=jdbc:postgresql://postgres:5432/vynlo_taste
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-vynlo-sistema}
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - vynlo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${NEXT_PUBLIC_FIREBASE_APP_ID}
    container_name: vynlo-frontend-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8081/api/v1
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - vynlo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # nginx (opcional) removido; Next.js serve diretamente na porta 3000

  # Monitoring - Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: vynlo-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - vynlo-network

  # Monitoring - Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: vynlo-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - vynlo-network

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  vynlo-network:
    driver: bridge