spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    enabled: false

# Firebase Configuration para desenvolvimento
firebase:
  config:
    path: firebase-service-account-dev.json

# Logging para desenvolvimento
logging:
  level:
    com.vynlotaste.financial: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

